export const FLOW_LEVEL = {
    NONE: "NONE",
    LIGHT: "LIGHT",
    MEDIUM: "MEDIUM",
    HEAVY: "HEAVY",
    SPOTTING: "SPOTTING"
}

export const MOOD_LEVEL = {
  HAPPY: "HAPPY",
  NEUTRAL: "NEUTRAL",
  SAD: "SAD",
  LOL: "LOL",
  IDK: "IDK",
  GREAT: "GREAT",
  SICK: "SICK",
  ANGRY: "ANGRY",
  LOVED: "LOVED"
}


export const CRAMP_LEVEL = {
  NEUTRAL: "NEUTRAL",
  BAD: "BAD",
  TERRIBLE: "TERRIBLE",
  GOOD: "GOOD",
  NONE: "NONE",
}

export const EXERCISE_TYPE =  {
  CARDIO: "CARDIO",
  YOGA: "YOGA",
  STRENGTH: "STRENGTH",
  BALL_SPORT: "BALL SPORT",
  MARTIAL_ARTS: "MARTIAL ARTS",
  WATER_SPORT: "WATER SPORT",
  CYCLE_SPORT: "CYCLE SPORT",
  RACKET_SPORT: "RACKET SPORT",
  WINTER_SPORT: "WINTER SPORT"
}
